# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Ramon Perez"
subtitle: "Personal Website"
title_separator: "|"
name: "Ramon Perez"
masthead_title: "My Website"


email: ramonpzg@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my site. Here you'll find a good mix of the things I'm up to.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ramonpzg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ramonpzg
repository: "ramonpzg/ramonpzg.github.io"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum" "sunrise"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/NSW
locale: "en-US"

logo: "/assets/images/bio-photo.png"
teaser: "/assets/images/husky_coffee.png"

include: ["_pages"]

search: true

# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


author:
  name   : "Ramon Perez"
  avatar : "/assets/images/ramon_headshot.png"
  bio    : "Freelance Data Professional"
  location: "Sydney, NSW, Australia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ramonpzg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ramonprz"
    - label: "Kaggle"
      icon: "fab fa-fw fa-kaggle"
      url: "https://linkedin.com/in/ramonprz"
    - label: "HuggingFace"
      icon: "fab fa-fw fa-face-smiling-hands"
      url: "https://linkedin.com/in/ramonprz"
    - label: "Streamlit"
      icon: "fab fa-fw fa-face-smiling-hands"
      url: "https://linkedin.com/in/ramonprz"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ramonpzg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/ramonprz"
    - label: "Kaggle"
      icon: "fa-brands fa-kaggle"
      url: "https://linkedin.com/in/ramonprz"
    - label: "HuggingFace"
      icon: "fa-thin fa-face-smiling-hands"
      url: "https://linkedin.com/in/ramonprz"

defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments:
        provider: "utterances"
        utterances:
          theme: "github-dark"
          issue_term: "pathname"
          label: "comment"
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/



# Other Collections
collections:
  # tutorials:
  #   output: true
  projects:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  workshops:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
# gems: [jekyll-mermaid]

# mermaid:
#   src: '/assets/js/mermaid.js'