title: "Productivity Tools"
description: "Collection of productivity tools, frameworks, and best practices for deep work."
tags: ["deep-work", "productivity", "tools"]
items:
  - name: "TodoIst"
    description: "Task management tool"
    url: "https://todoist.com/"
    category: "Task Management" 
  - name: "Rise Calendar"
    description: "Cross-platform calendar app"
    url: "https://risecalendar.com/"
    category: "Calendar" 
  - name: "Obsidian"
    description: "Extensible/Malleable note-taking app"
    url: "https://obsidian.md/"
    category: "Note-taking" 
  - name: "Affine"
    description: "Collaborative, local-first, notion-replacement note-taking app"
    url: "https://affine.pro/"
    category: "Note-taking" 
  - name: "1Password"
    description: "Password manager"
    url: "https://1password.com/"
    category: "Password Management" 
  - name: "Raindrop"
    description: "Bookmark manager"
    url: "https://raindrop.io/"
    category: "Bookmark Management" 
  - name: "Helix"
    description: "Modern terminal editor"
    url: "https://helix-editor.com/"
    category: "Terminal IDE" 
  - name: "Tldraw"
    description: "Collaborative whiteboard"
    url: "https://tldraw.com/"
    category: "Infinite Canvas" 
  - name: "OBS"
    description: "Open-source video recording and live streaming software"
    url: "https://obsproject.com/"
    category: "Video Recording" 
  - name: "Yazi"
    description: "💥 Blazing fast terminal file manager written in Rust, based on async I/O."
    url: "https://yazi-rs.github.io/"
    category: "Terminal File Manager"
  - name: "Pacseek"
    description: "Arch Linux TUI for searching and installing AUR packages"
    url: "https://github.com/moson-mo/pacseek"
    category: "Arch Linux"
  - name: "mpv"
    description: "Play videos from your terminal."
    url: "https://mpv.io/"
    category: "Media Player"
  - name: "OnlyOffice"
    description: "Microsoft Office alternative"
    url: "https://onlyoffice.com/"
    category: "Office Suite"
  - name: "Elia Chat"
    description: "A snappy, keyboard-centric terminal user interface for interacting with large language models."
    url: "https://github.com/darrenburns/elia"
    category: "Terminal Chat App"
  - name: "MarkText"
    description: "Nice-looking markdown editor"
    url: "https://www.marktext.cc/"
    category: "Markdown Editor"
  - name: "LibreChat"
    description: "AI chat app for your terminal"
    url: "https://www.librechat.ai/"
    category: "OSS AI Chat App"
  - name: "Perplexity AI"
    description: "AI search engine"
    url: "https://www.perplexity.ai/"
    category: "AI Search Engine"